### ISSUE TITLE
The quality model viewer did not show the metrics

### ISSUE THREAD

**Issue by aabherve** [q-rapids/qrapids-dashboard#111]
Hi,

It seams that the quality model viewer  (Assesment> QualityModel ) display only the Strategic Indicators and Factors.
The metric and her links with Factors are not display.

![Screenshot_2019-12-17 Q-Rapids](https://user-images.githubusercontent.com/15227604/71010394-0c5ccb00-20ec-11ea-93ac-fd1a2e500be9.png)

**Comment by alejandravv** [comment]
After analyzing the data from the elasticsearch used, we found that in index of relations there are some relations from factor to strategic indicator with evaluationDate equals 2019-11-05 and there is no relations for metrics on this date. 
So the solution of this problem is delete the mistaken data from relations index with this evaluationDate.

**Comment by lidix91** [comment]
Alex,

Please, close the issue.

Lidia
