### ISSUE TITLE
Quality Model weights

### ISSUE THREAD

**Issue by lidix91** [q-rapids/qrapids-dashboard#116]
The current version is showing the assessment in the nodes with weigths. 

This view should show:
- [x] non weighted values in nodes, the node should show the current assessment
- [x] the weights shown in the arrows should be represented as percentage

**Comment by alejandravv** [comment]
Now in Quality Model view, all nodes are shown without weight applied (current assessment). The edges between metric and factor have the corresponding percentage represented on it, and the edges between factors and strategic indicators have no label because the calculation used in this case is a normal average.
