### ISSUE TITLE
qr-alert fails to post alerts to dashboard

### ISSUE THREAD

**Issue by juhamoisala** [q-rapids/qrapids-dashboard#47]
When qr-alert script tries to post new alert to Q-Rapids/api/notifyAlert API returns response code 200 but POSTing fails. Returned message body shows that response code is 500. 

If clause in alerts.js is not reached and error is not visible when running qr-alert.sh
```
}, function (error, response, body) {
        if(error) console.log(error);
        else console.log(JSON.stringify(serobj)+" set to " + configfile.notification_service)
        //iconsole.log(body);
        //console.log(response);
});
```

I have seen two different errors returned by the API with different factors/metrics/SIs:

- could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement
- No enum constant qr.models.enumerations.Type.User Defined Rule

Example response:
```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8" />
    <title>Q-Rapids</title>
    <link rel="stylesheet" href="/Q-Rapids/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/Q-Rapids/css/styles.css" />
    <link rel="stylesheet" href="/Q-Rapids/css/auth/auth.css" />
    <link rel="shortcut icon" type="image/x-icon" href="/Q-Rapids/favicon.ico" />
    <script type="text/javascript" src="/Q-Rapids/js/lib/moment.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/lib/Chart.min.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/lib/angular.min.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/app/app.services.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/lib/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="/Q-Rapids/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/lib/sockjs.min.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/lib/stomp.min.js"></script>
    <link rel="stylesheet" href="/Q-Rapids/css/animate.css" />
    <script type="text/javascript" src="/Q-Rapids/js/lib/bootstrap-notify.min.js"></script>
    <script type="text/javascript" src="/Q-Rapids/js/notificationsHandler.js"></script>
</head>
<body>
<section id="error-control">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-lg-12" style="display: flex; align-items: center; justify-content: center; height: 80vh; width: 100%; flex-flow: column;">
            <div class="row">
                <div class="col-xs-12" style="margin-top: 10px; margin-left: 10px;">
                    <h2 class="title" style="color: #0177a6;">
                        <img class="container" src="/Q-Rapids/icons/qrapids.png" alt="qrapids logo" />
                        Q-Rapids: Quality-aware rapid software development
                    </h2>
                </div>
            </div>
            <h3 style="color: brown">
                URL <span>/error</span>
                Status: <span>500</span>
                <span style="color: #000;">could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement</span>
            </h3>
        </div>
    </div>
</section>
</body>
</html>
```

**Comment by marcoriol** [comment]
Looks like this issue may be related with the following piece of code: 
https://github.com/q-rapids/qrapids-alert/blob/master/rules/rules.js (line 21). 

Here it seems that an alert is created with the type "User defined Rule". But, this type doesn't exist in the dashboard, since the types are enums (METRIC, FACTOR, STRATEGIC_INDICATOR). I guess that this line of code explains the error "No enum constant qr.models.enumerations.Type.User Defined Rule"

@Rafal, could you please have a look at this? 

Related to that, in https://github.com/q-rapids/qrapids-alert/blob/master/utils/alerts.js there are also possible values that the Dashboard will not be able to process correctly. Those values are the category "General" and the project_id "unknown". I understand that those values are in case something is not properly set, but we are unsure of the behaviour of the dashboard when receiving such values. Hence, we are wondering if such alerts should be forwarded to the dasbhoard? (e.g. an alert without a project will not be displayed in the dashboard, similarly an alert of category GENERAL will not have QR patterns to solve them).

**Comment by lidix91** [comment]
integration issue

**Comment by lidix91** [comment]
it cannot be reproduced after version 0.3.3
